annual_return: 0.08
annual_standard_deviation: 0.12
annual_expense_ratio: 0.0095
annual_fed_funds_rate: 0.03
years_to_simulate: 10000
etfs: {
  1x: {multiple: 1},
  2x: {multiple: 2},
  3x: {multiple: 3}
}
blends: {
  '70_30': {
    1x: 0.7,
    3x: 0.3
  },
  '50_50': {
    1x: 0.5,
    3x: 0.5
  }
}